In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_excel("./england1920.xls")
df.head(10)

,team_name,score,result,date,possession_rate,shooting,effective_shooting,missed_shooting,blocked_shooting,freekick,cornerkick,offside,keeper_defense,passes_number,tackle,attack,threatening_attack,is_home
0,왓포드,1,0,29.06.2020 00:30,48,8,0,2,6,10,5,1,4,396,13,124,48,1
1,사우샘프턴,3,2,29.06.2020 00:30,52,11,7,3,1,17,3,1,0,460,20,131,46,0
2,아스톤 빌라,0,0,27.06.2020 20:30,48,11,1,8,2,18,2,0,1,423,8,110,39,1
3,울버햄튼,1,2,27.06.2020 20:30,52,9,2,6,1,17,2,2,1,464,10,106,53,0
4,첼시,2,2,26.06.2020 04:15,35,15,10,3,2,4,5,3,1,382,13,58,31,1
5,맨체스터 시티,1,0,26.06.2020 04:15,65,11,2,6,3,16,7,1,8,713,7,162,64,0
6,번리,1,2,26.06.2020 02:00,54,9,5,4,0,16,1,3,4,424,11,108,40,1
7,왓포드,0,0,26.06.2020 02:00,46,10,4,6,0,15,7,0,4,329,16,109,49,0
8,사우샘프턴,0,0,26.06.2020 02:00,53,12,3,7,2,16,4,2,3,435,17,112,54,1
9,아스날,2,2,26.06.2020 02:00,47,10,5,3,2,13,6,1,3,398,10,97,30,0

# 데이터 전처리

#### 시계열 형태로 변환

In [3]:
df['date'] = pd.to_datetime(df['date'], format='%d.%m.%Y %H:%M')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624 entries, 0 to 623
Data columns (total 18 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   team_name           624 non-null    object
 1   score               624 non-null    int64
 2   result              624 non-null    int64
 3   date                624 non-null    datetime64[ns]
 4   possession_rate     624 non-null    int64
 5   shooting            624 non-null    int64
 6   effective_shooting  624 non-null    int64
 7   missed_shooting     624 non-null    int64
 8   blocked_shooting    624 non-null    int64
 9   freekick            624 non-null    int64
 10  cornerkick          624 non-null    int64
 11  offside             624 non-null    int64
 12  keeper_defense      624 non-null    int64
 13  passes_number       624 non-null    int64
 14  tackle              624 non-null    int64
 15  attack              624 non-null    int64
 16  threatening_attack  624 non-null    int64
 17  is_home             624 non-null    int64
dtypes: datetime64[ns](1), int64(16), object(1)
memory usage: 87.9+ KB

In [4]:
df.head()

,team_name,score,result,date,possession_rate,shooting,effective_shooting,missed_shooting,blocked_shooting,freekick,cornerkick,offside,keeper_defense,passes_number,tackle,attack,threatening_attack,is_home
0,왓포드,1,0,2020-06-29 00:30:00,48,8,0,2,6,10,5,1,4,396,13,124,48,1
1,사우샘프턴,3,2,2020-06-29 00:30:00,52,11,7,3,1,17,3,1,0,460,20,131,46,0
2,아스톤 빌라,0,0,2020-06-27 20:30:00,48,11,1,8,2,18,2,0,1,423,8,110,39,1
3,울버햄튼,1,2,2020-06-27 20:30:00,52,9,2,6,1,17,2,2,1,464,10,106,53,0
4,첼시,2,2,2020-06-26 04:15:00,35,15,10,3,2,4,5,3,1,382,13,58,31,1

In [5]:
df.set_index('date', inplace = True)

In [6]:
df.head()

,team_name,score,result,possession_rate,shooting,effective_shooting,missed_shooting,blocked_shooting,freekick,cornerkick,offside,keeper_defense,passes_number,tackle,attack,threatening_attack,is_home
date,,,,,,,,,,,,,,,,,
2020-06-29 00:30:00,왓포드,1,0,48,8,0,2,6,10,5,1,4,396,13,124,48,1
2020-06-29 00:30:00,사우샘프턴,3,2,52,11,7,3,1,17,3,1,0,460,20,131,46,0
2020-06-27 20:30:00,아스톤 빌라,0,0,48,11,1,8,2,18,2,0,1,423,8,110,39,1
2020-06-27 20:30:00,울버햄튼,1,2,52,9,2,6,1,17,2,2,1,464,10,106,53,0
2020-06-26 04:15:00,첼시,2,2,35,15,10,3,2,4,5,3,1,382,13,58,31,1

team_name 명목형 변수를 제거하는 대신 전 시즌의 리그 순위를 이용하여 수치형 변수로 변환

In [7]:
df['team_name'].value_counts()

울버햄튼          32
사우샘프턴         32
왓포드           32
아스톤 빌라        32
뉴캐슬 Utd       31
셰필드U          31
번리            31
아스날           31
본머스           31
크리스탈팰리스       31
첼시            31
노르위치          31
브라이튼          31
레스터           31
웨스트햄          31
맨체스터 유나이티드    31
리버풀           31
에버튼           31
맨체스터 시티       31
토트넘           31
Name: team_name, dtype: int64

In [8]:
def ranking(name):
    if name == '맨체스터 시티':
        return 1
    elif name == '리버풀':
        return 2
    elif name == '첼시':
        return 3
    elif name == '토트넘':
        return 4
    elif name == '아스날':
        return 5
    elif name == '맨체스터 유나이티드':
        return 6
    elif name == '울버햄튼':
        return 7
    elif name == '에버튼':
        return 8
    elif name == '레스터':
        return 9
    elif name == '웨스트햄':
        return 10
    elif name == '왓포드':
        return 11
    elif name == '크리스탈팰리스':
        return 12
    elif name == '뉴캐슬 Utd':
        return 13
    elif name == '본머스':
        return 14
    elif name == '번리':
        return 15
    elif name == '사우샘프턴':
        return 16
    elif name == '브라이튼':
        return 17
    else:
        return 18

In [9]:
df['last_seson_ranking'] = df['team_name'].apply(ranking)
df.head()

,team_name,score,result,possession_rate,shooting,effective_shooting,missed_shooting,blocked_shooting,freekick,cornerkick,offside,keeper_defense,passes_number,tackle,attack,threatening_attack,is_home,last_seson_ranking
date,,,,,,,,,,,,,,,,,,
2020-06-29 00:30:00,왓포드,1,0,48,8,0,2,6,10,5,1,4,396,13,124,48,1,11
2020-06-29 00:30:00,사우샘프턴,3,2,52,11,7,3,1,17,3,1,0,460,20,131,46,0,16
2020-06-27 20:30:00,아스톤 빌라,0,0,48,11,1,8,2,18,2,0,1,423,8,110,39,1,18
2020-06-27 20:30:00,울버햄튼,1,2,52,9,2,6,1,17,2,2,1,464,10,106,53,0,7
2020-06-26 04:15:00,첼시,2,2,35,15,10,3,2,4,5,3,1,382,13,58,31,1,3

#### 데이터 분할

In [10]:
df_x = df.drop(columns = ['result','team_name'], axis=1)
df_x.head()

,score,possession_rate,shooting,effective_shooting,missed_shooting,blocked_shooting,freekick,cornerkick,offside,keeper_defense,passes_number,tackle,attack,threatening_attack,is_home,last_seson_ranking
date,,,,,,,,,,,,,,,,
2020-06-29 00:30:00,1,48,8,0,2,6,10,5,1,4,396,13,124,48,1,11
2020-06-29 00:30:00,3,52,11,7,3,1,17,3,1,0,460,20,131,46,0,16
2020-06-27 20:30:00,0,48,11,1,8,2,18,2,0,1,423,8,110,39,1,18
2020-06-27 20:30:00,1,52,9,2,6,1,17,2,2,1,464,10,106,53,0,7
2020-06-26 04:15:00,2,35,15,10,3,2,4,5,3,1,382,13,58,31,1,3

In [11]:
df_y = df.pop('result')
df_y.head()

date
2020-06-29 00:30:00    0
2020-06-29 00:30:00    2
2020-06-27 20:30:00    0
2020-06-27 20:30:00    2
2020-06-26 04:15:00    2
Name: result, dtype: int64

훈련, 평가 데이터 분할

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
train_x, test_x, train_y, test_y = train_test_split(df_x, df_y, test_size=0.33, random_state=42)

# 모델링

RandomForest

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
RF_model = RandomForestClassifier()

In [16]:
RF_fitted = RF_model.fit(train_x, train_y)

In [17]:
predicted_y = RF_fitted.predict(test_x)
predicted_y

array([0, 2, 0, 2, 0, 1, 2, 2, 2, 2, 1, 0, 0, 2, 2, 2, 0, 2, 0, 2, 0, 0,
       0, 0, 0, 2, 0, 2, 0, 0, 0, 2, 1, 2, 2, 2, 0, 0, 2, 2, 1, 0, 2, 0,
       0, 2, 0, 1, 2, 2, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0, 0, 0, 2, 0, 0,
       0, 1, 1, 2, 1, 2, 2, 0, 2, 2, 1, 2, 1, 0, 2, 0, 0, 0, 0, 0, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 2, 0,
       0, 2, 2, 2, 2, 2, 0, 0, 2, 1, 1, 2, 1, 0, 0, 0, 2, 1, 2, 0, 0, 0,
       2, 0, 2, 1, 2, 1, 0, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 2, 1, 0, 2, 2,
       0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 1, 2, 0, 0, 2, 0, 2, 2, 1, 0, 0,
       0, 2, 2, 2, 2, 1, 0, 0, 2, 1, 0, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2,
       0, 2, 1, 2, 1, 1, 0, 0], dtype=int64)

확률값으로 확인하기

In [18]:
RF_fitted.predict_proba(test_x)

array([[0.55, 0.3 , 0.15],
       [0.08, 0.11, 0.81],
       [0.62, 0.3 , 0.08],
       [0.05, 0.14, 0.81],
       [0.53, 0.36, 0.11],
       [0.33, 0.4 , 0.27],
       [0.25, 0.22, 0.53],
       [0.08, 0.23, 0.69],
       [0.07, 0.27, 0.66],
       [0.15, 0.11, 0.74],
       [0.35, 0.4 , 0.25],
       [0.76, 0.22, 0.02],
       [0.53, 0.42, 0.05],
       [0.06, 0.23, 0.71],
       [0.08, 0.14, 0.78],
       [0.23, 0.12, 0.65],
       [0.67, 0.3 , 0.03],
       [0.14, 0.09, 0.77],
       [0.79, 0.15, 0.06],
       [0.17, 0.3 , 0.53],
       [0.69, 0.19, 0.12],
       [0.56, 0.26, 0.18],
       [0.7 , 0.23, 0.07],
       [0.74, 0.2 , 0.06],
       [0.93, 0.03, 0.04],
       [0.27, 0.2 , 0.53],
       [0.66, 0.23, 0.11],
       [0.33, 0.16, 0.51],
       [0.5 , 0.39, 0.11],
       [0.55, 0.31, 0.14],
       [0.42, 0.36, 0.22],
       [0.15, 0.33, 0.52],
       [0.37, 0.48, 0.15],
       [0.15, 0.36, 0.49],
       [0.02, 0.01, 0.97],
       [0.14, 0.16, 0.7 ],
       [0.4 , 0.38, 0.22],
       [0.56, 0.2 , 0.24],
       [0.31, 0.33, 0.36],
       [0.29, 0.23, 0.48],
       [0.28, 0.64, 0.08],
       [0.52, 0.36, 0.12],
       [0.11, 0.21, 0.68],
       [0.39, 0.27, 0.34],
       [0.74, 0.21, 0.05],
       [0.16, 0.25, 0.59],
       [0.65, 0.28, 0.07],
       [0.28, 0.49, 0.23],
       [0.08, 0.16, 0.76],
       [0.23, 0.18, 0.59],
       [0.07, 0.16, 0.77],
       [0.48, 0.32, 0.2 ],
       [0.1 , 0.19, 0.71],
       [0.69, 0.22, 0.09],
       [0.21, 0.12, 0.67],
       [0.19, 0.2 , 0.61],
       [0.5 , 0.25, 0.25],
       [0.24, 0.21, 0.55],
       [0.43, 0.43, 0.14],
       [0.12, 0.14, 0.74],
       [0.6 , 0.25, 0.15],
       [0.73, 0.25, 0.02],
       [0.62, 0.2 , 0.18],
       [0.13, 0.11, 0.76],
       [0.6 , 0.26, 0.14],
       [0.86, 0.1 , 0.04],
       [0.56, 0.25, 0.19],
       [0.19, 0.56, 0.25],
       [0.28, 0.49, 0.23],
       [0.02, 0.2 , 0.78],
       [0.3 , 0.45, 0.25],
       [0.01, 0.06, 0.93],
       [0.27, 0.27, 0.46],
       [0.73, 0.16, 0.11],
       [0.1 , 0.21, 0.69],
       [0.24, 0.12, 0.64],
       [0.36, 0.5 , 0.14],
       [0.05, 0.09, 0.86],
       [0.41, 0.51, 0.08],
       [0.39, 0.35, 0.26],
       [0.09, 0.08, 0.83],
       [0.59, 0.29, 0.12],
       [0.68, 0.28, 0.04],
       [0.44, 0.42, 0.14],
       [0.63, 0.31, 0.06],
       [0.43, 0.28, 0.29],
       [0.09, 0.14, 0.77],
       [0.05, 0.09, 0.86],
       [0.22, 0.21, 0.57],
       [0.13, 0.34, 0.53],
       [0.05, 0.06, 0.89],
       [0.58, 0.26, 0.16],
       [0.22, 0.18, 0.6 ],
       [0.06, 0.16, 0.78],
       [0.85, 0.13, 0.02],
       [0.46, 0.29, 0.25],
       [0.14, 0.19, 0.67],
       [0.34, 0.42, 0.24],
       [0.56, 0.39, 0.05],
       [0.73, 0.19, 0.08],
       [0.49, 0.34, 0.17],
       [0.87, 0.12, 0.01],
       [0.08, 0.08, 0.84],
       [0.21, 0.49, 0.3 ],
       [0.1 , 0.18, 0.72],
       [0.72, 0.14, 0.14],
       [0.02, 0.11, 0.87],
       [0.68, 0.27, 0.05],
       [0.15, 0.33, 0.52],
       [0.77, 0.2 , 0.03],
       [0.69, 0.28, 0.03],
       [0.16, 0.32, 0.52],
       [0.19, 0.15, 0.66],
       [0.14, 0.15, 0.71],
       [0.23, 0.34, 0.43],
       [0.15, 0.17, 0.68],
       [0.52, 0.4 , 0.08],
       [0.66, 0.11, 0.23],
       [0.08, 0.12, 0.8 ],
       [0.41, 0.43, 0.16],
       [0.45, 0.52, 0.03],
       [0.05, 0.22, 0.73],
       [0.37, 0.43, 0.2 ],
       [0.61, 0.14, 0.25],
       [0.63, 0.33, 0.04],
       [0.44, 0.37, 0.19],
       [0.19, 0.31, 0.5 ],
       [0.36, 0.4 , 0.24],
       [0.2 , 0.3 , 0.5 ],
       [0.52, 0.38, 0.1 ],
       [0.54, 0.36, 0.1 ],
       [0.54, 0.32, 0.14],
       [0.12, 0.2 , 0.68],
       [0.64, 0.19, 0.17],
       [0.09, 0.17, 0.74],
       [0.36, 0.37, 0.27],
       [0.06, 0.25, 0.69],
       [0.26, 0.59, 0.15],
       [0.6 , 0.23, 0.17],
       [0.81, 0.16, 0.03],
       [0.48, 0.41, 0.11],
       [0.55, 0.35, 0.1 ],
       [0.72, 0.19, 0.09],
       [0.62, 0.25, 0.13],
       [0.11, 0.07, 0.82],
       [0.07, 0.08, 0.85],
       [0.84, 0.11, 0.05],
       [0.74, 0.26, 0.  ],
       [0.08, 0.23, 0.69],
       [0.13, 0.14, 0.73],
       [0.34, 0.47, 0.19],
       [0.61, 0.3 , 0.09],
       [0.06, 0.16, 0.78],
       [0.27, 0.15, 0.58],
       [0.48, 0.35, 0.17],
       [0.6 , 0.27, 0.13],
       [0.79, 0.17, 0.04],
       [0.42, 0.34, 0.24],
       [0.1 , 0.18, 0.72],
       [0.63, 0.19, 0.18],
       [0.5 , 0.33, 0.17],
       [0.44, 0.44, 0.12],
       [0.16, 0.2 , 0.64],
       [0.57, 0.25, 0.18],
       [0.53, 0.24, 0.23],
       [0.34, 0.46, 0.2 ],
       [0.24, 0.11, 0.65],
       [0.56, 0.26, 0.18],
       [0.5 , 0.25, 0.25],
       [0.06, 0.26, 0.68],
       [0.6 , 0.35, 0.05],
       [0.29, 0.33, 0.38],
       [0.17, 0.24, 0.59],
       [0.38, 0.44, 0.18],
       [0.56, 0.28, 0.16],
       [0.94, 0.03, 0.03],
       [0.53, 0.29, 0.18],
       [0.25, 0.17, 0.58],
       [0.21, 0.37, 0.42],
       [0.08, 0.14, 0.78],
       [0.17, 0.26, 0.57],
       [0.35, 0.47, 0.18],
       [0.74, 0.25, 0.01],
       [0.76, 0.17, 0.07],
       [0.06, 0.1 , 0.84],
       [0.24, 0.39, 0.37],
       [0.46, 0.3 , 0.24],
       [0.15, 0.27, 0.58],
       [0.46, 0.39, 0.15],
       [0.06, 0.07, 0.87],
       [0.44, 0.34, 0.22],
       [0.79, 0.17, 0.04],
       [0.71, 0.21, 0.08],
       [0.7 , 0.24, 0.06],
       [0.25, 0.27, 0.48],
       [0.56, 0.32, 0.12],
       [0.57, 0.37, 0.06],
       [0.08, 0.08, 0.84],
       [0.81, 0.13, 0.06],
       [0.05, 0.25, 0.7 ],
       [0.32, 0.42, 0.26],
       [0.03, 0.13, 0.84],
       [0.43, 0.52, 0.05],
       [0.36, 0.38, 0.26],
       [0.45, 0.38, 0.17],
       [0.84, 0.1 , 0.06]])

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, predicted_y)

array([[61,  9,  8],
       [28, 10, 16],
       [ 7,  7, 60]], dtype=int64)